TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_TOKEN_SECRET = ''

SENDGRID_API_USER = ''
SENDGRID_API_KEY = ''
FROM_ADDRESS = ''
TO_ADDRESS = ''

STATHAT_KEY = ''